# Generated by Django 2.0.5 on 2019-08-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190822_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name_plural': 'Читатели'},
        ),
        migrations.AddField(
            model_name='persons',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Books'),
        ),
    ]
