# Generated by Django 2.0.5 on 2019-08-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190823_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='book',
        ),
        migrations.AddField(
            model_name='books',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Persons'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
