# Generated by Django 2.0.5 on 2019-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190823_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='person',
        ),
        migrations.AddField(
            model_name='books',
            name='person',
            field=models.ManyToManyField(blank=True, to='app.Persons'),
        ),
    ]
