# Generated by Django 2.0.5 on 2019-08-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190823_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='books', to='app.Persons'),
        ),
    ]
