# Generated by Django 2.0.5 on 2019-09-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190830_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
